/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ceccd4098c3969c3ec2c939a316ce3e9)
interface __BaseEnv_Env {
  BUCKET: R2Bucket;
  DB: D1Database;
  ADMIN_TOKEN: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/server');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, 'ADMIN_TOKEN'>> {}
}
